import {
  Pen,
  ImageIcon,
  ShoppingCart,
  Code,
  Briefcase,
  Heart,
  Zap,
  Globe,
} from "lucide-react";

export const categories = [
  {
    id: "writing",
    title: "Writing",
    description: "Creative writing, copywriting, and content creation prompts",
    icon: Pen,
    promptCount: 150,
  },
  {
    id: "image",
    title: "Image Generation",
    description: "AI art, photography, and visual content prompts",
    icon: ImageIcon,
    promptCount: 120,
  },
  {
    id: "ecommerce",
    title: "E-commerce",
    description: "Product descriptions, marketing copy, and sales prompts",
    icon: ShoppingCart,
    promptCount: 85,
  },
  {
    id: "coding",
    title: "Coding",
    description: "Programming, debugging, and technical documentation prompts",
    icon: Code,
    promptCount: 95,
  },
  {
    id: "business",
    title: "Business",
    description: "Strategy, planning, and professional communication prompts",
    icon: Briefcase,
    promptCount: 110,
  },
  {
    id: "lifestyle",
    title: "Lifestyle",
    description: "Health, fitness, travel, and personal development prompts",
    icon: Heart,
    promptCount: 75,
  },
  {
    id: "productivity",
    title: "Productivity",
    description: "Task management, goal setting, and efficiency prompts",
    icon: Zap,
    promptCount: 65,
  },
  {
    id: "social-media",
    title: "Social Media",
    description: "Content creation, engagement, and marketing prompts",
    icon: Globe,
    promptCount: 90,
  },
];

export const pricingPlans = [
  {
    name: "Free",
    price: 0,
    period: "forever",
    description: "Perfect for getting started with AI prompts",
    features: [
      "Access to 5 free prompts",
      "Basic prompt categories",
      "Copy and edit functionality",
      "Community support",
    ],
    buttonText: "Get Started",
    buttonVariant: "outline" as const,
    popular: false,
  },
  {
    name: "Pro",
    price: 9,
    period: "month",
    description: "Unlock the full potential of AI prompting",
    features: [
      "Access to 500+ premium prompts",
      "All prompt categories",
      "Advanced prompt editor",
      "Priority support",
      "New prompts added weekly",
      "Export prompts to various formats",
      "Custom prompt collections",
      "API access",
    ],
    buttonText: "Subscribe Now",
    buttonVariant: "default" as const,
    popular: true,
  },
];

export const prompts = [
  {
    id: "1",
    title: "Creative Blog Post Writer",
    content:
      "Write a compelling blog post about [TOPIC] that engages readers and provides valuable insights. The tone should be [TONE] and target [AUDIENCE]. Include an attention-grabbing headline, introduction, main points, and conclusion. Make sure to include actionable tips and real-world examples related to [TOPIC]. The post should be approximately [WORD_COUNT] words long.",
    category: "writing",
    categoryName: "Writing",
    isLocked: false,
    variables: [
      {
        name: "TOPIC",
        type: "text" as const,
        label: "Blog Topic",
        placeholder: "e.g., AI in Healthcare, Remote Work Tips",
        required: true,
        description: "The main subject of your blog post",
      },
      {
        name: "TONE",
        type: "select" as const,
        label: "Writing Tone",
        options: [
          "Professional",
          "Casual",
          "Friendly",
          "Authoritative",
          "Conversational",
        ],
        required: true,
        description: "The tone and style of your writing",
      },
      {
        name: "AUDIENCE",
        type: "dropdown" as const,
        label: "Target Audience",
        options: [
          "Beginners",
          "Professionals",
          "Students",
          "General Public",
          "Experts",
        ],
        required: true,
        description: "Who is your primary audience?",
      },
      {
        name: "WORD_COUNT",
        type: "number" as const,
        label: "Word Count",
        placeholder: "1000",
        required: false,
        description: "Approximate length of the blog post",
      },
    ],
    thumbnail: null,
    type: "text",
  },
  {
    id: "2",
    title: "Product Description Generator",
    content:
      "Create a persuasive product description for [PRODUCT] that highlights key features, benefits, and appeals to the target audience. The product is priced at [PRICE] and is perfect for [TARGET_AUDIENCE]. Focus on [SELLING_POINTS] and maintain a [TONE] tone throughout. Include a compelling call-to-action that encourages immediate purchase.",
    category: "ecommerce",
    categoryName: "E-commerce",
    isLocked: false,
    variables: [
      {
        name: "PRODUCT",
        type: "text" as const,
        label: "Product Name",
        placeholder: "e.g., Wireless Bluetooth Headphones",
        required: true,
      },
      {
        name: "PRICE",
        type: "text" as const,
        label: "Product Price",
        placeholder: "e.g., $99.99, €79.99",
        required: true,
      },
      {
        name: "TARGET_AUDIENCE",
        type: "select" as const,
        label: "Target Audience",
        options: [
          "Tech Enthusiasts",
          "Fitness Lovers",
          "Professionals",
          "Students",
          "Parents",
          "Seniors",
        ],
        required: true,
      },
      {
        name: "SELLING_POINTS",
        type: "textarea" as const,
        label: "Key Selling Points",
        placeholder:
          "List the main features and benefits that make this product special",
        required: true,
        description: "Highlight what makes your product unique",
      },
      {
        name: "TONE",
        type: "dropdown" as const,
        label: "Marketing Tone",
        options: [
          "Exciting",
          "Professional",
          "Trustworthy",
          "Luxurious",
          "Budget-friendly",
        ],
        required: true,
      },
    ],
    thumbnail: null,
    type: "text",
  },
  {
    id: "7",
    title: "Fantasy Landscape Generator",
    content:
      "Create a breathtaking [STYLE] fantasy landscape featuring [MAIN_SUBJECT] with [LIGHTING] lighting and [ATMOSPHERE] atmosphere. The scene should include [ELEMENTS] and be rendered in [QUALITY] quality with [COLOR_PALETTE] color palette. Add [MAGICAL_EFFECTS] to enhance the mystical feeling. Camera angle: [CAMERA_ANGLE], composition: [COMPOSITION]. Reference URL for inspiration: [REFERENCE_URL].",
    category: "image",
    categoryName: "Image Generation",
    isLocked: false,
    variables: [
      {
        name: "STYLE",
        type: "select" as const,
        label: "Art Style",
        options: [
          "Digital Art",
          "Oil Painting",
          "Watercolor",
          "Concept Art",
          "Photorealistic",
        ],
        required: true,
      },
      {
        name: "MAIN_SUBJECT",
        type: "text" as const,
        label: "Main Subject",
        placeholder: "e.g., floating islands, ancient castle, mystical forest",
        required: true,
      },
      {
        name: "LIGHTING",
        type: "dropdown" as const,
        label: "Lighting Style",
        options: [
          "Golden Hour",
          "Ethereal",
          "Dramatic",
          "Soft",
          "Moonlight",
          "Magical Glow",
        ],
        required: true,
      },
      {
        name: "ATMOSPHERE",
        type: "select" as const,
        label: "Atmosphere",
        options: [
          "Mystical",
          "Serene",
          "Epic",
          "Mysterious",
          "Peaceful",
          "Dramatic",
        ],
        required: true,
      },
      {
        name: "ELEMENTS",
        type: "textarea" as const,
        label: "Scene Elements",
        placeholder:
          "Describe additional elements like waterfalls, ruins, creatures, etc.",
        required: false,
        description: "Additional details to include in the scene",
      },
      {
        name: "QUALITY",
        type: "select" as const,
        label: "Image Quality",
        options: [
          "4K",
          "8K Ultra-detailed",
          "High Resolution",
          "Cinematic Quality",
        ],
        required: true,
      },
      {
        name: "COLOR_PALETTE",
        type: "text" as const,
        label: "Color Palette",
        placeholder: "e.g., warm purples and blues, earth tones",
        required: false,
      },
      {
        name: "MAGICAL_EFFECTS",
        type: "text" as const,
        label: "Magical Effects",
        placeholder:
          "e.g., floating particles, energy streams, glowing elements",
        required: false,
      },
      {
        name: "CAMERA_ANGLE",
        type: "dropdown" as const,
        label: "Camera Angle",
        options: [
          "Wide Shot",
          "Close-up",
          "Bird's Eye View",
          "Low Angle",
          "High Angle",
        ],
        required: true,
      },
      {
        name: "COMPOSITION",
        type: "select" as const,
        label: "Composition Style",
        options: [
          "Rule of Thirds",
          "Centered",
          "Leading Lines",
          "Symmetrical",
          "Dynamic",
        ],
        required: true,
      },
      {
        name: "REFERENCE_URL",
        type: "url" as const,
        label: "Reference Image URL",
        placeholder: "https://example.com/reference-image.jpg",
        required: false,
        description: "Optional reference image for inspiration",
      },
    ],
    thumbnail: "/images/fantasy-landscape-example.png",
    type: "image",
    exampleValues: {
      STYLE: "Digital Art",
      MAIN_SUBJECT: "floating islands connected by magical bridges",
      LIGHTING: "Golden Hour",
      ATMOSPHERE: "Mystical",
      ELEMENTS: "cascading waterfalls, ancient ruins, glowing crystals",
      QUALITY: "8K Ultra-detailed",
      COLOR_PALETTE: "warm purples, blues, and gold",
      MAGICAL_EFFECTS:
        "floating particles of light, aurora-like energy streams",
      CAMERA_ANGLE: "Wide Shot",
      COMPOSITION: "Rule of Thirds",
      REFERENCE_URL: "",
    },
  },
];
